# Generated by Django 5.2.3 on 2025-07-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recom', '0002_alter_job_options_remove_job_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
