# Generated by Django 5.2.3 on 2025-07-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_recom', '0003_job_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_job_type',
        ),
    ]
