# Generated by Django 5.2.3 on 2025-09-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_recom", "0004_remove_userprofile_preferred_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
