# Generated by Django 5.2.3 on 2025-11-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_recom", "0006_jobrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobinteraction",
            name="interaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("view", "View"),
                    ("apply", "Apply"),
                    ("save", "Save"),
                    ("rating", "Rating"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
